export { default as TopBar } from "./TopBar";
export { default as ContentHome } from "./ContentMain";
export { default as SimpleSlider} from "./Carousel";
export { default as MainPage } from "./MainPage";
export { default as ConteinerCarousel } from "./ConteinerCarousel"; 
export { default as BookCard } from "./BookCard";
export { default as Modal } from "./Modal";
export { default as TitleBook } from "./Title";
export { default as FieldSynopse } from "./FieldSynopse";
export { default as Button } from "./Button";
export { default as SectionSynpse } from "./DivSynopse";
export { default as BookParagraph } from "./Paragraph";
export { default as Select } from "./Select";