export { default as TopBar } from "./TopBar";
export { default as ContentHome } from "./ContentMain";
export { default as SimpleSlider} from "./Carousel";
export { default as MainPage } from "./MainPage";
export { default as ConteinerCarousel } from "./ConteinerCarousel"; 
export { default as BookCard } from "./BookCard";
export { default as Modal } from "./Modal";
export { default as TitleBook } from "./Title";
export { default as FieldSynopse } from "./FieldSynopse";
export { default as Button } from "./Button";
export { default as SectionSynpse } from "./DivSynopse";
export { default as BookParagraph } from "./Paragraph";
export { default as Select } from "./Select";
export { default as MainBody } from "./MainBody";
export { default as PaperSimulation} from "./PaperSimulation";
export { default as Background } from "./Background";
export { default as Logo } from "./Logo";
export { default as ConteinerMenu } from "./ConteinerMenu";
export { default as ButtomMenu } from "./ButtomMenu";
export { default as AuthorMsg } from   './AuthorMsg';